apiVersion: v1
kind: Service
metadata:
  name: locust-service
  namespace: mlops
spec:
  type: ClusterIP
  selector:
    app: locust
  ports:
    - port: 8089
      targetPort: 8089
      protocol: TCP
