apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: mlops
data:
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  MLFLOW_S3_ENDPOINT_URL: "http://minio-service:9000"
  MODEL_NAME: "diabetes-model"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_NAME: "inference_db"
