apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: mlops
type: Opaque
stringData:
  DB_USER: "mlops_user"
  DB_PASSWORD: "mlops1234"
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"
