apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: mlops
spec:
  type: ClusterIP
  selector:
    app: inference-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
