apiVersion: batch/v1
kind: Job
metadata:
  name: minio-create-bucket
  namespace: mlops
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc:latest
          command:
            - /bin/sh
            - -c
            - |
              mc alias set myminio http://minio-service:9000 minioadmin minioadmin123
              mc mb --ignore-existing myminio/mlflow-artifacts
              echo "Bucket mlflow-artifacts creado."
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
