apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: mlops
type: Opaque
stringData:
  POSTGRES_USER: "mlops_user"
  POSTGRES_PASSWORD: "mlops_password"
  POSTGRES_DB: "mlops_db"
