apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.1.0
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: grafana-secret
          env:
            - name: GF_SERVER_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: grafana-config
                  key: GF_SERVER_HTTP_PORT
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources/datasources.yml
              subPath: datasources.yml
            - name: dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
              subPath: dashboards.yml
            - name: alerting
              mountPath: /etc/grafana/provisioning/alerting/api-alerts.yml
              subPath: api-alerts.yml
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards/api-dashboard.json
              subPath: api-dashboard.json
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
        - name: datasources
          configMap:
            name: grafana-config
            items:
              - key: datasources.yml
                path: datasources.yml
        - name: dashboards-provider
          configMap:
            name: grafana-config
            items:
              - key: dashboards.yml
                path: dashboards.yml
        - name: alerting
          configMap:
            name: grafana-config
            items:
              - key: api-alerts.yml
                path: api-alerts.yml
        - name: dashboards
          configMap:
            name: grafana-config
            items:
              - key: api-dashboard.json
                path: api-dashboard.json
