apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secret
  namespace: mlops
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "minioadmin"
  AWS_SECRET_ACCESS_KEY: "minioadmin123"
  BACKEND_STORE_URI: "postgresql+psycopg2://mlflow_user:mlflow1234@mlflow-postgres-service:5432/mlflow_db"
