apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: mlops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: cccortesh/mlops-streamlit:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          envFrom:
            - configMapRef:
                name: streamlit-config
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /_stcore/health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
